name: ds_segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.7.4.post0
  - async-timeout=3.0.1
  - attrs=21.2.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - catalogue=2.0.6
  - certifi=2021.10.8
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - colorama=0.4.4
  - cryptography=35.0.0
  - cymem=2.0.6
  - cython-blis=0.7.5
  - dataclasses=0.8
  - et_xmlfile=1.0.1
  - google-api-core=2.2.2
  - google-api-python-client=2.30.0
  - google-auth=2.3.3
  - google-auth-httplib2=0.1.0
  - google-auth-oauthlib=0.4.6
  - googleapis-common-protos=1.53.0
  - httplib2=0.20.2
  - icc_rt=2019.0.0
  - idna=3.1
  - intel-openmp=2021.4.0
  - jinja2=3.0.3
  - langcodes=3.2.1
  - libprotobuf=3.19.1
  - libzlib=1.2.11
  - markupsafe=2.0.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - murmurhash=1.0.6
  - numpy=1.21.2
  - numpy-base=1.21.2
  - oauthlib=3.1.1
  - openpyxl=3.0.9
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.4
  - pathy=0.6.1
  - pip=21.0.1
  - preshed=3.0.6
  - protobuf=3.19.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydantic=1.8.2
  - pyjwt=2.3.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.5
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - pyu2f=0.1.5
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - ruamel.yaml=0.17.17
  - ruamel.yaml.clib=0.2.2
  - scipy=1.7.1
  - setuptools=58.0.4
  - shellingham=1.4.0
  - simplejson=3.17.5
  - six=1.16.0
  - smart_open=5.2.1
  - spacy=3.2.0
  - spacy-legacy=3.0.8
  - spacy-loggers=1.0.1
  - sqlite=3.36.0
  - srsly=2.4.2
  - thinc=8.0.12
  - tqdm=4.62.3
  - typer=0.4.0
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - uritemplate=3.0.1
  - urllib3=1.26.7
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wasabi=0.8.2
  - wheel=0.37.0
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - yarl=1.7.2
  - zlib=1.2.11
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.2.0/en_core_web_md-3.2.0-py3-none-any.whl
