name: matchmaking
channels:
  - conda-forge
  - anaconda
dependencies:
  - scipy
  - pip
  - google-api-python-client
  - google-auth-httplib2
  - google-auth-oauthlib
  - spyder-kernels
  - numpy
  - pandas
  - openpyxl
  - pyyaml
  - hdbscan
  - matplotlib
  - spacy
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.2.5/en_core_web_md-2.2.5.tar.gz#egg=en_core_web_mda